### ISSUE TITLE
How can I download the Liferay Server to the local cache?

### ISSUE THREAD

**Issue by CrazyBunQnQ** [gamerson/liferay-intellij-plugin#24]
## 请问我如何才能将 Liferay Server 下载到 local cache 中呢？
您好，我在 initBundle 的时候下载 Liferay Server 很慢，需要几个小时，所以手动下载了 Liferay Server 文件，并放到对应目录：
![dir](http://wx2.sinaimg.cn/large/a6e9cb00ly1fsjspn5tysj21kw0nah65.jpg)
但是再次执行 initBundle 时还是重新下载 Liferay Server 文件并将我下好的文件覆盖了。
您在 README 中写道：
>It will take several minutes to download the latest Liferay Server from remote if you don’t have the local cache

请问我如何才能将 Liferay Server 下载到 local cache 中呢？

## Hello, I'm sorry my English is a bit poor...
I was slow to download while running the initBundle, So I downloaded Liferay Server separately, and put it in the directory in the picture. 
![dir](http://wx2.sinaimg.cn/large/a6e9cb00ly1fsjspn5tysj21kw0nah65.jpg)
But when I run the initBundle again it reloads the file and overrided my file...

The README said:
>It will take several minutes to download the latest Liferay Server from remote if you don’t have the local cache

So how can I download the Liferay Server to the `local cache`?

**Comment by jtydhr88** [comment]
hey @CrazyBunQnQ 
你可以把liferay portal的zip放到你的liferay workspace项目的根目录下，解压缩后将文件夹重命名为bundles，然后在intellij里面添加liferay server的时候能自动识别了，不需要再运行initBundle

**Comment by CrazyBunQnQ** [comment]
@jtydhr88 谢谢，可以啦！
